spring:
    application:
        name: programmerTranslator
serve:
    port: 8080
ydCloud:
    translate:
        ydUrl: https://openapi.youdao.com/api
        appKey: xxxx
        appSecret: xxxx
baidu:
    translate:
        appKey: xxxx
        appSecret: xxxx